export const Pages = [
  ["Quick Start", "/"],
  ["Billing", "/billing"],
  ["Payment Method", "/billing/payment-method"],
  ["Manage Funds", "/billing/funds"],
  ["Add-on", "/billing/add-on"],
  ["Invoices & Usages", "/billing/invoices"],
  ["Credits", "/billing/credits"],
  ["Upgrade to Pro with Credit Card", "/billing/upgrade/credit-card"],
  ["Upgrade to Pro with Polygon", "/billing/upgrade/polygon"],
  ["Upgrade to Pro with Optimism", "/billing/upgrade/optimism"],
  ["Upgrade to Pro with BSC", "/billing/upgrade/bsc"],
  ["Upgrade to Pro with Gnosis", "/billing/upgrade/gnosis"],
  ["Upgrade to Pro with Arbitrum", "/billing/upgrade/arbitrum"],
  ["Upgrade to Pro with Avalanche", "/billing/upgrade/avalanche"],
  ["Upgrade to Pro with Filecoin", "/billing/upgrade/filecoin"],
  ["Upgrade to Pro with Mantle", "/billing/upgrade/mantle"],
  ["Upgrade to Pro with Base", "/billing/upgrade/base"],
  ["Upgrade to Pro with Linea", "/billing/upgrade/linea"],
  ["Upgrade to Pro with Solana", "/billing/upgrade/solana"],
  ["Organization", "/organization"],
  ["Members & Roles", "/organization/roles"],
  ["Settings", "/organization/settings"],
  ["Edge Network", "/edge-network"],
  ["CDN", "/edge-network/cdn"],
  ["Caching", "/edge-network/caching"],
  ["Compression & Encryption", "/edge-network/compression"],
  ["Regions & Routing", "/edge-network/regions"],
  ["Spheron Compute", "/compute"],
  ["Compute", "/compute/cluster/compute"],
  ["Accelerate", "/compute/cluster/accelerate"],
  ["Logs & Activity", "/compute/instance/logs"],
  ["Instance Domains", "/compute/instance/domain"],
  ["Instance Settings", "/compute/instance/settings"],
  ["Compute Usage", "/compute/usage"],
  ["Compute Type", "/compute/type"],
  ["On Demand", "/compute/type/on-demand"],
  ["Autoscale", "/compute/type/autoscale"],
  ["Compute Plans", "/compute/plans/compute-plans"],
  ["Accelerate Plans", "/compute/plans/accelerate-plans"],
  ["Server Guide", "/server-guide"],
  ["Deploy Next App", "/server-guide/nextjs"],
  ["Deploy Rust App", "/server-guide/rust"],
  ["Deploy Django App", "/server-guide/django"],
  ["Deploy Go App", "/server-guide/go"],
  ["Deploy Rails App", "/server-guide/rails"],
  ["Deploy Express App", "/server-guide/express"],
  ["Deploy Nest App", "/server-guide/nest"],
  ["Marketplace App Guide", "/marketplace-guide"],
  ["Deploy MongoDB", "/marketplace-guide/mongodb"],
  ["Deploy Redis", "/marketplace-guide/redis"],
  ["Deploy PostgreSQL", "/marketplace-guide/postgresql"],
  ["Deploy MySQL", "/marketplace-guide/mysql"],
  ["Deploy Grafana", "/marketplace-guide/grafana"],
  ["Deploy Vault", "/marketplace-guide/vault"],
  ["Deploy Drupal", "/marketplace-guide/drupal"],
  ["Deploy Jupyter Notebook", "/marketplace-guide/jupyter"],
  ["Deploy VSCode Server", "/marketplace-guide/vscode"],
  ["Deploy Minecraft Server", "/marketplace-guide/minecraft"],
  ["Deploy TensorFlow GPU", "/marketplace-guide/tensorflow"],
  ["Spheron SDK", "/sdk"],
  ["Compute SDK", "/sdk/compute"],
  ["FVM Deal Utils SDK", "/sdk/fvm-deal-utils"],
  ["Spheron CLI", "/cli"],
  ["Spheron API", "/rest-api"],
  ["Github Actions", "/github-actions"],
  ["Instance Update Action", "/github-actions/instance-update-action"],
  ["Spheron Terraform", "/terraform"],
];
