export const Pages = [
  ["Quick Start", "/"],
  ["Billing", "/billing"],
  ["Connect Wallet", "/billing/wallet"],
  ["Manage Funds", "/billing/funds"],
  ["Bonuses", "/billing/bonus"],
  ["Invoices & Usages", "/billing/invoices"],
  ["Coupons", "/billing/coupons"],
  ["Upgrade to Pro", "/billing/upgrade"],
  ["Upgrade to Pro with Polygon", "/billing/upgrade/polygon"],
  ["Upgrade to Pro with Optimism", "/billing/upgrade/optimism"],
  ["Upgrade to Pro with BSC", "/billing/upgrade/bsc"],
  ["Upgrade to Pro with Gnosis", "/billing/upgrade/gnosis"],
  ["Upgrade to Pro with Arbitrum", "/billing/upgrade/arbitrum"],
  ["Upgrade to Pro with Avalanche", "/billing/upgrade/avalanche"],
  ["Upgrade to Pro with Solana", "/billing/upgrade/solana"],
  ["Organization", "/organization"],
  ["Members & Roles", "/organization/roles"],
  ["Settings", "/organization/settings"],
  ["Git Provider & Logs", "/static/deployment/logs"],
  ["Git Automations", "/static/deployment/automation"],
  ["Manage Deployments", "/static/deployment/deployments"],
  ["Preview, Pinning & Deal creation", "/static/deployment/preview"],
  ["Domains", "/static/projects/domain"],
  ["Handshake Domains", "/static/projects/handshake"],
  ["ENS Domains", "/static/projects/ens"],
  ["HTTPS", "/static/projects/https"],
  ["Environments", "/static/projects/environments"],
  ["Env Variables", "/static/projects/variables"],
  ["Password Protected Domains", "/static/projects/private"],
  ["CDN", "/static/edge/cdn"],
  ["Caching", "/static/edge/caching"],
  ["Compression & Encryption", "/static/edge/compression"],
  ["Regions & Routing", "/static/edge/regions"],
  ["Cluster", "/compute/cluster"],
  ["Logs & Activity", "/compute/instance/logs"],
  ["Instance Domains", "/compute/instance/domain"],
  ["Instance Settings", "/compute/instance/settings"],
  ["Compute Usage", "/compute/usage"],
  ["Dedicated Gateways", "/gateways/dedicated"],
  ["Public Gateway", "/gateways/public-gateway"],
  ["Framework Guide", "/framework-guide"],
  ["Deploy Angular App", "/framework-guide/deploy-angular"],
  ["Deploy Brunch App", "/framework-guide/deploy-brunch"],
  ["Deploy Docusarus App", "/framework-guide/deploy-docusarus"],
  ["Deploy Gatsby App", "/framework-guide/deploy-gatsby"],
  ["Deploy Hugo App", "/framework-guide/deploy-hugo"],
  ["Deploy Ionic React App", "/framework-guide/deploy-ireact"],
  ["Deploy Next.js App", "/framework-guide/deploy-next"],
  ["Deploy Nuxt.js App", "/framework-guide/deploy-nuxt"],
  ["Deploy Preact App", "/framework-guide/deploy-preact"],
  ["Deploy React App", "/framework-guide/deploy-react"],
  ["Deploy Sanity App", "/framework-guide/deploy-sanity"],
  ["Deploy Stencil App", "/framework-guide/deploy-stencil"],
  ["Deploy Svelte App", "/framework-guide/deploy-svelte"],
  ["Deploy Vanilla App", "/framework-guide/deploy-vanilla"],
  ["Deploy Vue App", "/framework-guide/deploy-vue"],
  ["Deploy Ionic Angular App", "/framework-guide/deploy-iangular"],
  ["Deploy Vite App", "/framework-guide/deploy-vite"],
  ["Server Guide", "/server-guide"],
  ["Deploy Next App", "/server-guide/nextjs"],
  ["Deploy Rust App", "/server-guide/rust"],
  ["Deploy Django App", "/server-guide/django"],
  ["Deploy Go App", "/server-guide/go"],
  ["Deploy Rails App", "/server-guide/rails"],
  ["Deploy Express App", "/server-guide/express"],
  // ["Deploy Nest App", "/server-guide/nest"],
  ["Marketplace App Guide", "/marketplace-guide"],
  ["Deploy MongoDB", "/marketplace-guide/mongodb"],
  ["Deploy Redis", "/marketplace-guide/redis"],
  ["Deploy PostgreSQL", "/marketplace-guide/postgresql"],
  ["Deploy MySQL", "/marketplace-guide/mysql"],
  ["Deploy Grafana", "/marketplace-guide/grafana"],
  ["Deploy Vault", "/marketplace-guide/vault"],
  ["Deploy IPFS Node", "/marketplace-guide/ipfs"],
  ["Deploy Substrate Node", "/marketplace-guide/substrate"],
  ["Deploy Stride Node", "/marketplace-guide/stride"],
  ["Deploy Hypersign Node", "/marketplace-guide/hypersign"],
  ["Deploy Kyve Node", "/marketplace-guide/kyve"],
  ["Deploy Reef Node", "/marketplace-guide/reef"],
  ["Deploy Mantle DTL", "/marketplace-guide/mantle-dtl"],
  ["Deploy Mantle Verifier", "/marketplace-guide/mantle-verifier"],
  ["Deploy Drupal", "/marketplace-guide/drupal"],
  ["Deploy Deso Node", "/marketplace-guide/deso"],
  ["Deploy MassBit Gateway", "/marketplace-guide/massbit-gateway"],
  ["Deploy Arbitrum One", "/marketplace-guide/arbitrum-one"],
  ["Deploy Filecoin Mainnet", "/marketplace-guide/filecoin"],
  ["Spheron SDK", "/sdk"],
  ["Storage SDK", "/sdk/storage"],
  ["Browser Upload SDK", "/sdk/browser"],
  ["Compute SDK", "/sdk/compute"],
  ["Site SDK", "/sdk/site"],
  ["Spheron CLI", "/cli"],
  ["Spheron API", "/rest-api"],
  ["Github Actions", "/github-actions"],
  ["Instance Update Action", "/github-actions/instance-update-action"],
  ["Spheron Terraform", "/terraform"],
];
