export const Pages = [
  ["Quick Start", "/"],
  ["Billing", "/billing"],
  ["Connect Wallet", "/billing/wallet"],
  ["Manage Funds", "/billing/funds"],
  ["Bonuses", "/billing/bonus"],
  ["Invoices & Usages", "/billing/invoices"],
  ["Coupons", "/billing/coupons"],
  ["Organization", "/organization"],
  ["Members & Roles", "/organization/roles"],
  ["Settings", "/organization/settings"],
  ["Git Provider & Logs", "/static/deployment/logs"],
  ["Preview & Pinning", "/static/deployment/preview"],
  ["Manage Deployments", "/static/deployment/deployments"],
  ["Domains", "/static/projects/domain"],
  ["Handshake Domains", "/static/projects/handshake"],
  ["ENS Domains", "/static/projects/ens"],
  ["HTTPS", "/static/projects/https"],
  ["Environments", "/static/projects/environments"],
  ["Env Variables", "/static/projects/variables"],
  ["Password Protected Domains", "/static/projects/private"],
  ["CDN", "/static/edge/cdn"],
  ["Caching", "/static/edge/caching"],
  ["Compression & Encryption", "/static/edge/compression"],
  ["Regions & Routing", "/static/edge/regions"],
];
