export const Pages = [
  ["Getting Started", "/"],
  ["Spheron Protocol", "/spheron-protocol"],
  ["Service Provider", "/spheron-protocol/service-provider"],
  ["Deployment Lifecycle", "/spheron-protocol/deployment-lifecycle"],
  ["Payment System", "/spheron-protocol/payment-system"],
  ["Billing", "/billing"],
  ["Payment Method", "/billing/payment-method"],
  ["Manage Funds", "/billing/funds"],
  ["Credits", "/billing/credits"],
  ["Invoices & Usages", "/billing/invoices"],
  [
    "Topup Compute with Web3 Wallet",
    "/billing/compute/topup-compute-funds-web3",
  ],
  [
    "Topup Compute with Credit Card",
    "/billing/compute/topup-compute-funds-creditcard",
  ],
  ["View Compute Usage", "/billing/compute/compute-usage"],
  ["Organization", "/organization"],
  ["Open Community Page", "/organization/community"],
  ["Members & Roles", "/organization/roles"],
  ["Provider Onboarding", "/provider-onboarding"],
  ["Setup Ansible", "/provider-onboarding/setup-ansible"],
  ["Setup Provider", "/provider-onboarding/setup-provider"],
  ["Test Deployment", "/provider-onboarding/test-deployment"],
  ["Spheron Compute", "/compute"],
  ["Compute", "/compute/cluster/compute"],
  ["Accelerate", "/compute/cluster/accelerate"],
  ["Logs & Activity", "/compute/instance/logs"],
  ["Instance Domains", "/compute/instance/domain"],
  ["Instance Settings", "/compute/instance/settings"],
  ["Compute Usage", "/compute/usage"],
  ["Compute Type", "/compute/type"],
  ["On Demand", "/compute/type/on-demand"],
  ["Autoscale", "/compute/type/autoscale"],
  ["Compute Plans", "/compute/plans/compute-plans"],
  ["Accelerate Plans", "/compute/plans/accelerate-plans"],
  ["Edge Network", "/compute/edge-network"],
  ["CDN", "/compute/edge-network/cdn"],
  ["Caching", "/compute/edge-network/caching"],
  ["Compression & Encryption", "/compute/edge-network/compression"],
  ["Regions & Routing", "/compute/edge-network/regions"],
  ["Server Guide", "/server-guide"],
  ["Deploy Next App", "/server-guide/nextjs"],
  ["Deploy Rust App", "/server-guide/rust"],
  ["Deploy Django App", "/server-guide/django"],
  ["Deploy Go App", "/server-guide/go"],
  ["Deploy Rails App", "/server-guide/rails"],
  ["Deploy Express App", "/server-guide/express"],
  ["Deploy Nest App", "/server-guide/nest"],
  ["Marketplace App Guide", "/marketplace-guide"],
  ["Deploy MongoDB", "/marketplace-guide/mongodb"],
  ["Deploy Redis", "/marketplace-guide/redis"],
  ["Deploy PostgreSQL", "/marketplace-guide/postgresql"],
  ["Deploy MySQL", "/marketplace-guide/mysql"],
  ["Deploy Grafana", "/marketplace-guide/grafana"],
  ["Deploy Vault", "/marketplace-guide/vault"],
  ["Deploy Drupal", "/marketplace-guide/drupal"],
  ["Deploy Jupyter Notebook", "/marketplace-guide/jupyter"],
  ["Deploy VSCode Server", "/marketplace-guide/vscode"],
  ["Deploy Minecraft Server", "/marketplace-guide/minecraft"],
  ["Deploy TensorFlow GPU", "/marketplace-guide/tensorflow"],
  ["Spheron SDK", "/sdk"],
  ["Compute SDK", "/sdk/compute"],
  ["Spheron CLI", "/cli"],
  ["Spheron API", "/rest-api"],
  ["Github Actions", "/github-actions"],
  ["Instance Update Action", "/github-actions/instance-update-action"],
  ["Spheron Terraform", "/terraform"],
  ["General Information", "/general-info"],
];
